main:
  - name: Homepage
    url: /
    weight: 10
  - name: Profile & CV
    url: experience/
    weight: 20
  - name: Research Experiences
    url: research/
    weight: 30
  - name: Extracurricular Activities
    url: extracurricular/
    weight: 40
  - name: Conferences
    url: /#talks
    weight: 50
  - name: News
    url: /#news
    weight: 60
